### PR TITLE
Update to use Azure SDK modules

### LINKED ISSUE #35: Support authenticating with managed identity

### PR DESCRIPTION
**Pull request by kichristensen**
Update the Azure SDK modules as Autorest is legacy, see https://learn.microsoft.com/en-us/azure/developer/go/azure-sdk-authorization, for more information.

The result is that the custom credentials functions is no longer needed, simplifying the code.

A downside is that this custom prefixes are no easily supported, but Microsoft have standardized everything be prefixed with `AZURE_`, and the possibility to changed the prefix was not documented, so it could be considered okay to remove this functionality, please let me know what you think.

Also fixes #35

### CODE REVIEW

**Comment by Doommius** [comment]
@kichristensen was this merged elsewhere ?

**Comment by kichristensen** [comment]
@Doommius I honestly cannot remember why I closed this one. But it is not merged somewhere else as far as I can see

**Comment by Doommius** [comment]
I noticed that the doc mentions it being able to handle az cli Auth. I assume that means it's possible to pass managed identity via azure resources as well? At least that's the use case I'm looking at to remove credentials that can be exposed/leaked.

**Comment by kichristensen** [comment]
@Doommius If you can get the managed identity token to be resolved inside the container, it should be possible, at least according to the code, but haven't tested it.
It will most likely involve running the container with host network enabled

**Pull request closed without merging**
